"""empty message

Revision ID: c566e6e93e7c
Revises: 61ac562a6603
Create Date: 2020-05-13 01:57:51.769158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c566e6e93e7c'
down_revision = '61ac562a6603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('show_artistId_fkey', 'show', type_='foreignkey')
    op.drop_constraint('show_venueId_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    op.drop_column('show', 'artistId')
    op.drop_column('show', 'venueId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venueId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('show', sa.Column('artistId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_venueId_fkey', 'show', 'venue', ['venueId'], ['id'])
    op.create_foreign_key('show_artistId_fkey', 'show', 'artist', ['artistId'], ['id'])
    op.drop_column('show', 'venue_id')
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###
